name: music_analysis_pipeline
version: 1.0.0
config-version: 2
profile: music_analysis_pipeline
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
vars:
  artists: read_parquet('/home/sergio/dev/python/music-analysis-pipeline/datalake/parquet/artists.parquet/*.parquet')
  genre: read_parquet('/home/sergio/dev/python/music-analysis-pipeline/datalake/parquet/genre.parquet/*.parquet')
models:
  music_analysis_pipeline: null